#!/usr/bin/env perl
use v5.36;
#use open ':std', ':encoding(UTF-8)';
use Sq -sig => 1;
use Getopt::Long::Descriptive;

my ($opt, $usage) = describe_options(
    'Usage: pick_random [-n 10]',
    ['n=i',    'Amount to show',     { default => 1 }],
    ['help|h', 'Print this message', { shortcircuit => 1 }]
);

if ( $opt->help ) {
    print $usage->text;
    exit;
}

Sq->fs->recurse('.')->keep(call 'is_file')->to_array->shuffle->take($opt->n)->iter(sub($file) {
    print $file, "\n";
});
