#!/usr/bin/env perl
use v5.36;
#use open ':std', ':encoding(UTF-8)';

for my $file ( @ARGV ) {
    my $orig = $file;
    my $new  = $file =~ s/\. [^\.]+ \z/.ogg/xr;
    system('ffmpeg', '-vn', '-i', $orig, '-q:a', 8, $new);
}
